create table if not exists public.emojis (
  id bigint generated by default as identity primary key,
  image_url text not null,
  prompt text not null,
  likes_count numeric null default 0,
  creator_user_id text not null,
  created_at timestamp with time zone null default now()
);
