create table if not exists public.emoji_likes (
  id bigint generated by default as identity primary key,
  emoji_id bigint not null,
  user_id text not null,
  created_at timestamp with time zone null default current_timestamp
);
